apiVersion: apps/v1
kind: Deployment
metadata:
  name: departement-microservice-deployment
  labels:
    app: departement-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: departement-microservice
  template:
    metadata:
      labels:
        app: departement-microservice
    spec:
      containers:
      - name: departement-microservice-container
        image: marouanedbibih/rh-departement-microservice:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 9001